# Generated by Django 2.0.3 on 2018-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='sexo',
            field=models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M')], max_length=1),
        ),
    ]
