# Generated by Django 2.0.3 on 2018-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_auto_20180329_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='sexo',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
        migrations.AlterField(
            model_name='registro',
            name='votos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
