# Generated by Django 2.0.3 on 2018-03-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_auto_20180330_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif', models.IntegerField()),
                ('direccion_fiscal', models.CharField(max_length=500)),
                ('telefono1', models.IntegerField()),
                ('telefono2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='id_editora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.editora'),
        ),
    ]
