# Generated by Django 2.0.3 on 2018-03-31 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyecto', '0004_auto_20180330_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id_editora',
        ),
        migrations.AddField(
            model_name='registro',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
