# Generated by Django 2.0.3 on 2018-03-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0005_auto_20180331_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editora',
        ),
    ]
