# Generated by Django 2.0.3 on 2018-03-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0006_delete_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='resumen',
            field=models.CharField(default='Resumen', max_length=500),
        ),
    ]
