# Generated by Django 2.0.3 on 2018-03-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0007_registro_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='resumen',
            field=models.CharField(default='', max_length=500),
        ),
    ]
