# Generated by Django 2.0.3 on 2022-07-31 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyecto', '0008_auto_20180331_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
                ('fecha_recepcion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('descripcion', models.CharField(default=None, max_length=500)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('proveedor', models.CharField(default=None, max_length=100)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
