# Generated by Django 2.0.3 on 2022-07-31 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyecto', '0009_registroproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroproducto',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='registroproducto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
