# Generated by Django 2.0.3 on 2022-07-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0011_auto_20220731_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_producto',
            name='lote',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_producto',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
