# Generated by Django 2.0.3 on 2022-07-31 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyecto', '0012_auto_20220731_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(default=None, max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='registro_producto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='registro_producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='registro_producto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='registro_producto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.productos'),
        ),
    ]
