# Generated by Django 2.0.3 on 2022-07-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0013_auto_20220731_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_producto',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
