# Generated by Django 2.0.3 on 2022-07-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0015_auto_20220731_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_producto',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
